---
# tasks file for mariadb
- name: install MariaDB
  yum:
    name: mariadb-server
    state: present

- name: configure MariaDB
  template: src=sonarqube.cnf.j2 dest=/etc/my.cnf.d/sonarqube.cnf

- name: enable MariaDB service
  systemd:
    name: mariadb
    enabled: yes
