---
- name: upgrade all packages
  yum:
    name: "*"
    state: latest

- name: install additional packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
      - unzip
      - procps-ng
