---
- name: "copy {{ tool }} config"
  template:
    src: "{{ role_path }}/templates/vault-server.hcl.j2"
    dest: "/opt/hashicorp/{{ tool }}/config/vault-server.hcl"
    owner: consul

- name: "enable {{ tool }} service"
  systemd:
    name: "{{ tool }}"
    state: started
    enabled: yes
