---
nexus_default_admin_password: admin123
nexus_admin_password: p@ssword

nexus_karaf_data: /mnt/persistent/nexus3

nexus_default_port: 8081
docker_hosted_port: 9080
docker_proxy_port: 9081
docker_group_port: 9082

docker_blob_store: "{{ nexus_karaf_data }}/blobs/docker"

docker_store_conf:
  blob_store: "{{ docker_blob_store }}"
  strict_content_validation: true
  version_policy: release
  layout_policy: strict
  write_policy: allow_once

docker_proxy_conf:
  name: docker-proxy
  http_port: "{{ docker_proxy_port }}"
  v1_enabled: false
  index_type: "HUB"
  proxy_url: "https://registry.docker.io"
  use_nexus_certificates_to_access_index: false

docker_hosted_conf:
  name: docker-hosted
  http_port: "{{ docker_hosted_port }}"
  v1_enabled: false

docker_group_conf:
  name: docker-group
  http_port: "{{ docker_group_port }}"
  v1_enabled: false

ldap_name: "K LDAP"
ldap_protocol: "ldaps"
ldap_hostname: "ldap.example.com"
ldap_port: 636
ldap_auth: "simple"
ldap_auth_username: "username"
ldap_auth_password: "password"
ldap_search_base: "dc=example,dc=com"
ldap_user_base_dn: "ou=users"
ldap_user_filter: "(cn=*)"
ldap_user_object_class: "inetOrgPerson"
ldap_user_id_attribute: "uid"
ldap_user_real_name_attribute: "cn"
ldap_user_email_attribute: "mail"
ldap_group_base_dn: "ou=groups"
ldap_group_object_class: "posixGroup"
ldap_group_id_attribute: "cn"
ldap_group_member_attribute: "memberUid"
ldap_group_member_format: "${username}"
