---
nexus_default_admin_password: admin123
nexus_admin_password: p@ssword

nexus_karaf_data: /mnt/persistent/nexus3

nexus_default_port: 8081
docker_hosted_port: 9080
docker_proxy_port: 9081
docker_group_port: 9082

docker_blob_store: "{{ nexus_karaf_data }}/blobs/docker"

docker_store_conf:
  blob_store: "{{ docker_blob_store }}"
  strict_content_validation: true
  version_policy: release
  layout_policy: strict
  write_policy: allow_once

docker_proxy_conf:
  name: docker-proxy
  http_port: "{{ docker_proxy_port }}"
  v1_enabled: false
  index_type: "HUB"
  proxy_url: "https://registry.docker.io"
  use_nexus_certificates_to_access_index: false

docker_hosted_conf:
  name: docker-hosted
  http_port: "{{ docker_hosted_port }}"
  v1_enabled: false

docker_group_conf:
  name: docker-group
  http_port: "{{ docker_group_port }}"
  v1_enabled: false

ldap_conf:
  name: "K LDAP"
  protocol: "ldaps"
  hostname: "ldap.example.com"
  port: 636
  auth: "simple"
  auth_username: "username"
  auth_password: "password"
  search_base: "dc=example,dc=com"
  user_base_dn: "ou=users"
  user_filter: "(cn=*)"
  user_object_class: "inetOrgPerson"
  user_id_attribute: "uid"
  user_real_name_attribute: "cn"
  user_email_attribute: "mail"
  group_base_dn: "ou=groups"
  group_object_class: "groupOfNames"
  group_id_attribute: "cn"
  group_member_attribute: "memberOf"
  group_member_format: "${username}"
