---
# tasks file for mysql
- name: install mysql
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - http://repo.mysql.com/mysql57-community-release-el7.rpm
    - mysql-server
    - python2-mysql

- name: configure mysql
  template: src=sonarqube.cnf.j2 dest=/etc/my.cnf.d/sonarqube.cnf

- name: enable mysql service
  systemd:
    name: mysqld
    state: started
    enabled: yes

- name: disallow root login remotely
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost')
  changed_when: false

- name: remove test database and access to it
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DROP DATABASE test
    - DELETE FROM mysql.db WHERE Db LIKE 'test%'
    - FLUSH PRIVILEGES
  changed_when: false
  ignore_errors: true

- name: delete anonymous mysql users
  mysql_user:
    user: ""
    state: "absent"

- name: set root password
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    host: localhost
    state: present

- name: create sonarqube database
  mysql_db:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: sonarqube
    collation: utf8_bin
    state: present

- name: create sonarqube user
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    user: sonarqube
    password: "{{ sonarqube_user_password }}"
    host: "%"
    priv: "sonarqube.*:ALL"
    state: present

- name: stop mysql service
  systemd:
    name: mysqld
    state: stopped
    enabled: yes
