---
# tasks file for mysql
- name: add mysql repository
  yum:
    name: "http://repo.mysql.com/mysql57-community-release-el7.rpm"
    state: present

- name: install mysql
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - mysql-community-server
    - MySQL-python

- name: allow my.cnf includedir
  lineinfile:
    path: /etc/my.cnf
    insertafter: '^pid-file'
    line: "!includedir /etc/my.cnf.d"

- name: configure mysql
  template:
    src: "sonarqube.cnf.j2"
    dest: "/etc/my.cnf.d/sonarqube.cnf"

- name: Initialize mysql datadir
  command: "mysqld --initialize-insecure --user=mysql"

- name: enable mysql service
  systemd:
    name: mysqld
    state: started
    enabled: yes

- name: set root password
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    host: localhost
    state: present

- name: delete anonymous mysql users
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    user: ""
    state: "absent"

- name: create sonarqube database
  mysql_db:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: sonarqube
    collation: utf8_bin
    state: present

- name: create sonarqube user
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    user: sonarqube
    password: "{{ sonarqube_user_password }}"
    host: "%"
    priv: "sonarqube.*:ALL"
    state: present

- name: stop mysql service
  systemd:
    name: mysqld
    state: stopped
    enabled: yes
