---
- name: create sonarqube user
  user:
    name: sonarqube
    state: present
    home: "{{ sonarqube_dir }}"

- name: install sonarqube
  unarchive:
    src: "{{ sonarqube_url }}"
    dest: "{{ sonarqube_dir }}"
    owner: sonarqube
    group: sonarqube
    remote_src: yes

- name: copy sonarqube.service
  template:
    src: "{{ role_path }}/templates/sonarqube.service.j2"
    dest: "/etc/systemd/system/sonarqube.service"

- name: set Xmx in nexus.vmoptions
  lineinfile:
    path: /opt/sonatype/nexus/bin/nexus.vmoptions
    regexp: "^-Xmx"
    line: "-Xmx{{ nexus_Xmx }}"

- name: enable sonarqube service
  systemd:
    name: sonarqube
    enabled: yes
